### Fuzzing ATTACK 증강 설명
+ (데이터, 시작 시점, 끝나는 시점) 입력 받아서 랜덤 값 생성 
+ ID는 존재하는 ID중 랜덤하게 생성,  각 Datafield 들은 랜덤하게 16진수 2자리씩 생성
+ 기존 공격에서 DLC 가 모두 8, 증강도 DLC=8 인것만 생성

### 사용방법
+ (데이터, 시작 시점, 끝나는 지점)을 입력

In [8]:
import pandas as pd
# 최대 줄 수 설정
pd.set_option('display.max_rows', 5000)
# 최대 열 수 설정
pd.set_option('display.max_columns', 5000)
import random

In [9]:
fname = "Pro_Cybersecurity_Car_Hacking_D_training-0.csv"
data = pd.read_csv(fname)

In [10]:
def fuzzing(df,start,end):
    total_count = len(df)
    start_index = int((total_count / 100) * start)
    end_index = int((total_count / 100) * end)
    adf = df
    # 초기 index
    count = start_index +2
    while True:
        if count > end_index:
            break
            
        #TIME 생성
        Time = adf["Timestamp"][count] + (adf["Timestamp"][count-2] - adf["Timestamp"][count-1])
            
        #랜덤 ID 생성
        ID_pool = list(set(list(adf["Arbitration_ID"].values))) # ID 중복 제거해서 리스트 생성
        tem = random.randrange(len(ID_pool))
        ran_ID = ID_pool[tem]
    
        #랜던 Datafield 생성
        ran_datafield =[]
        string_pool = "0123456789ABCDEF"
        for i in range(8):
            tem = random.choice(string_pool) + random.choice(string_pool)
            ran_datafield.append(tem)
        
        
        #형식 맞춰주기
        fuzzing = [Time]+ [ran_ID] +[8]+ ran_datafield + ["Fuzzing"]
        #fuzzing.append("Attack")
        
        #행에 추가해주기
        tem_s =pd.Series(fuzzing,index=['Timestamp','Arbitration_ID','DLC','Data_1',"Data_2","Data_3","Data_4","Data_5","Data_6","Data_7","Data_8","Class"])
        print(tem_s)
        front = adf[:count]
        back = adf[count:]
        front = front.append(tem_s,ignore_index = True)
        adf = pd.concat([front,back])
        
        #attack 간격 조정
        interval = random.randrange(1,8)
        count += interval
        
    return adf

In [11]:
test = fuzzing(data,0,0.1)

Timestamp         1597707827
Arbitration_ID           164
DLC                        8
Data_1                    CD
Data_2                    66
Data_3                    05
Data_4                    83
Data_5                    03
Data_6                    B8
Data_7                    B4
Data_8                    35
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           412
DLC                        8
Data_1                    38
Data_2                    3D
Data_3                    94
Data_4                    60
Data_5                    ED
Data_6                    92
Data_7                    46
Data_8                    D4
Class                Fuzzing
dtype: object
Timestamp         5    1597707827
5    1597707827
Name: Timestam...
Arbitration_ID                                                  412
DLC                                                               8
Data_1                                                           B6
Data_2                                                           6B
Data_3                                                           25
Data_4                                                           86
Data_5                                                           F5
Data_6                                                           08
Data_7                                                           86
Data_8                                                           1B
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           57F
DLC                        8
Data_1                    A8
Data_2                    26
Data_3                    99
Data_4                    F6
Data_5                    80
Data_6                    84
Data_7                    B7
Data_8                    96
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           44E
DLC                        8
Data_1                    F9
Data_2                    7D
Data_3                    6A
Data_4                    A6
Data_5                    2B
Data_6                    24
Data_7                    BC
Data_8                    4F
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           485
DLC                        8
Data_1                    4E
Data_2                    44
Data_3                    80
Data_4                    02
Data_5                    AC
Data_6                    92
Data_7                    09
Data_8                    8D
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           4CB
DLC                        8
Data_1                    A6
Data_2                    82
Data_3                    D6
Data_4                    F1
Data_5                    3A
Data_6                    42
Data_7                    51
Data_8                    4C
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           4A9
DLC                        8
Data_1                    14
Data_2                    8A
Data_3                    D7
Data_4                    8D
Data_5                    53
Data_6                    22
Data_7                    42
Data_8                    10
Class                Fuzzing
dtype: object
Timestamp         37    1597707827
37    1597707827
Name: Timest...
Arbitration_ID                                                  368
DLC                                                               8
Data_1                                                           3A
Data_2                                                           2F
Data_3                                                           99
Data_4                                                           59
Data_5                                                           C4
Data_6                                                           AD
Data_7                                                           85
Data_8                                                           89
Class                                                       Fuzzing
dtype: object
Timestamp         39    37    1597707827
37    1597707827
Name: ...
Arbitration_ID                                                  48A
DLC                                                               8
Data_1                                                           16
Data_2                                                           91
Data_3                                                           96
Data_4                                                           82
Data_5                                                           43
Data_6                                                           C4
Data_7                                                           2A
Data_8                                                           91
Class                                                       Fuzzing
dtype: object
Timestamp         40                                            ...
Arbitration_ID                                                  367
DLC                                                               8
Data_1                                                           9A
Data_2                                                           A8
Data_3                                                           B8
Data_4                                                           80
Data_5                                                           D8
Data_6                                                           60
Data_7                                                           37
Data_8                                                           64
Class                                                       Fuzzing
dtype: object
Timestamp         42    40                                      ...
Arbitration_ID                                                  356
DLC                                                               8
Data_1                                                           B1
Data_2                                                           0B
Data_3                                                           C9
Data_4                                                           94
Data_5                                                           13
Data_6                                                           7E
Data_7                                                           B4
Data_8                                                           EC
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           391
DLC                        8
Data_1                    30
Data_2                    0E
Data_3                    58
Data_4                    0B
Data_5                    9D
Data_6                    1F
Data_7                    9B
Data_8                    B5
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           50E
DLC                        8
Data_1                    DD
Data_2                    9C
Data_3                    EB
Data_4                    06
Data_5                    44
Data_6                    3C
Data_7                    4F
Data_8                    BF
Class                Fuzzing
dtype: object
Timestamp         53    NaN
53    NaN
54    NaN
54    NaN
Name: ...
Arbitration_ID                                                  559
DLC                                                               8
Data_1                                                           28
Data_2                                                           4A
Data_3                                                           49
Data_4                                                           83
Data_5                                                           0D
Data_6                                                           12
Data_7                                                           33
Data_8                                                           F6
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           220
DLC                        8
Data_1                    7E
Data_2                    10
Data_3                    7A
Data_4                    3E
Data_5                    45
Data_6                    B3
Data_7                    D9
Data_8                    74
Class                Fuzzing
dtype: object

Timestamp         1597707827
Arbitration_ID           4F1
DLC                        8
Data_1                    0D
Data_2                    61
Data_3                    89
Data_4                    24
Data_5                    5C
Data_6                    6F
Data_7                    74
Data_8                    3C
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           366
DLC                        8
Data_1                    25
Data_2                    BE
Data_3                    73
Data_4                    D1
Data_5                    E3
Data_6                    6F
Data_7                    D8
Data_8                    6F
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           368
DLC                        8
Data_1                    19
Data_2                    CF
Data_3                    33
Data_4                    ED
Data_5                    E0
Data_6                    AC
Data_7                    E7
Data_8                    F4
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           4A7
DLC                        8
Data_1                    25
Data_2                    26
Data_3                    96
Data_4                    53
Data_5                    C0
Data_6                    F4
Data_7                    D7
Data_8                    33
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           153
DLC                        8
Data_1                    9C
Data_2                    F8
Data_3                    7F
Data_4                    4D
Data_5                    65
Data_6                    2D
Data_7                    7C
Data_8                    F0
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           490
DLC                        8
Data_1                    23
Data_2                    2F
Data_3                    0A
Data_4                    A5
Data_5                    C2
Data_6                    43
Data_7                    1D
Data_8                    7B
Class                Fuzzing
dtype: object
Timestamp         88    1597707827
88    1597707827
Name: Timest...
Arbitration_ID                                                  484
DLC                                                               8
Data_1                                                           7C
Data_2                                                           C0
Data_3                                                           9D
Data_4                                                           CB
Data_5                                                           77
Data_6                                                           17
Data_7                                                           C8
Data_8                                                           C4
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           50C
DLC                        8
Data_1                    04
Data_2                    6B
Data_3                    F6
Data_4                    05
Data_5                    43
Data_6                    4A
Data_7                    65
Data_8                    59
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           2B0
DLC                        8
Data_1                    E1
Data_2                    E4
Data_3                    1B
Data_4                    D3
Data_5                    30
Data_6                    61
Data_7                    7E
Data_8                    0C
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           568
DLC                        8
Data_1                    40
Data_2                    D6
Data_3                    74
Data_4                    6F
Data_5                    DA
Data_6                    45
Data_7                    6B
Data_8                    22
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           5BE
DLC                        8
Data_1                    2F
Data_2                    F3
Data_3                    0B
Data_4                    70
Data_5                    DF
Data_6                    94
Data_7                    EB
Data_8                    76
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           57F
DLC                        8
Data_1                    90
Data_2                    95
Data_3                    96
Data_4                    52
Data_5                    A5
Data_6                    6B
Data_7                    60
Data_8                    1C
Class                Fuzzing
dtype: object
Timestamp         113    NaN
113    NaN
114    NaN
114    NaN
Na...
Arbitration_ID                                                  50E
DLC                                                               8
Data_1                                                           ED
Data_2                                                           02
Data_3                                                           0E
Data_4                                                           1C
Data_5                                                           2A
Data_6                                                           A1
Data_7                                                           2E
Data_8                                                           D6
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           421
DLC                        8
Data_1                    B9
Data_2                    35
Data_3                    AF
Data_4                    DB
Data_5                    A8
Data_6                    E9
Data_7                    54
Data_8                    65
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           544
DLC                        8
Data_1                    6E
Data_2                    E1
Data_3                    84
Data_4                    3D
Data_5                    42
Data_6                    D6
Data_7                    BD
Data_8                    42
Class                Fuzzing
dtype: object
Timestamp         124    1597707827
124    1597707827
Name: Time...
Arbitration_ID                                                  251
DLC                                                               8
Data_1                                                           7E
Data_2                                                           AC
Data_3                                                           AB
Data_4                                                           F1
Data_5                                                           A9
Data_6                                                           04
Data_7                                                           2E
Data_8                                                           72
Class                                                       Fuzzing
dtype: object
Timestamp         125                                           ...
Arbitration_ID                                                  4C9
DLC                                                               8
Data_1                                                           6D
Data_2                                                           9D
Data_3                                                           25
Data_4                                                           7B
Data_5                                                           85
Data_6                                                           2D
Data_7                                                           54
Data_8                                                           8A
Class                                                       Fuzzing
dtype: object
Timestamp         126    124    NaN
124    NaN
Name: Timestamp, ...
Arbitration_ID                                                  470
DLC                                                               8
Data_1                                                           3C
Data_2                                                           69
Data_3                                                           6F
Data_4                                                           7C
Data_5                                                           B6
Data_6                                                           B3
Data_7                                                           60
Data_8                                                           B3
Class                                                       Fuzzing
dtype: object

Timestamp         1597707827
Arbitration_ID           48A
DLC                        8
Data_1                    56
Data_2                    25
Data_3                    DC
Data_4                    96
Data_5                    9D
Data_6                    6D
Data_7                    33
Data_8                    EE
Class                Fuzzing
dtype: object
Timestamp         131    NaN
131    NaN
132    NaN
132    NaN
Na...
Arbitration_ID                                                   43
DLC                                                               8
Data_1                                                           5B
Data_2                                                           F6
Data_3                                                           50
Data_4                                                           BA
Data_5                                                           85
Data_6                                                           45
Data_7                                                           04
Data_8                                                           26
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           367
DLC                        8
Data_1                    90
Data_2                    61
Data_3                    C4
Data_4                    1B
Data_5                    46
Data_6                    7B
Data_7                    13
Data_8                    7E
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           559
DLC                        8
Data_1                    A3
Data_2                    0C
Data_3                    4A
Data_4                    44
Data_5                    10
Data_6                    69
Data_7                    3D
Data_8                    92
Class                Fuzzing
dtype: object
Timestamp         141    1597707827
141    1597707827
Name: Time...
Arbitration_ID                                                  368
DLC                                                               8
Data_1                                                           C0
Data_2                                                           BD
Data_3                                                           06
Data_4                                                           6A
Data_5                                                           71
Data_6                                                           1C
Data_7                                                           3E
Data_8                                                           BD
Class                                                       Fuzzing
dtype: object
Timestamp         143    141    1597707827
141    1597707827
Nam...
Arbitration_ID                                                  48C
DLC                                                               8
Data_1                                                           C8
Data_2                                                           32
Data_3                                                           28
Data_4                                                           18
Data_5                                                           6C
Data_6                                                           0D
Data_7                                                           FA
Data_8                                                           20
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           541
DLC                        8
Data_1                    EB
Data_2                    58
Data_3                    34
Data_4                    48
Data_5                    AE
Data_6                    5D
Data_7                    ED
Data_8                    0D
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           2B0
DLC                        8
Data_1                    36
Data_2                    E4
Data_3                    22
Data_4                    68
Data_5                    F6
Data_6                    A4
Data_7                    08
Data_8                    3B
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           559
DLC                        8
Data_1                    F3
Data_2                    52
Data_3                    39
Data_4                    3D
Data_5                    45
Data_6                    82
Data_7                    11
Data_8                    7D
Class                Fuzzing
dtype: object
Timestamp         154    NaN
154    NaN
155    NaN
155    NaN
Na...
Arbitration_ID                                                  568
DLC                                                               8
Data_1                                                           1A
Data_2                                                           96
Data_3                                                           D7
Data_4                                                           28
Data_5                                                           7A
Data_6                                                           4A
Data_7                                                           8D
Data_8                                                           32
Class                                                       Fuzzing
dtype: object
Timestamp         155                                           ...
Arbitration_ID                                                  2B0
DLC                                                               8
Data_1                                                           DA
Data_2                                                           27
Data_3                                                           E4
Data_4                                                           17
Data_5                                                           1A
Data_6                                                           6C
Data_7                                                           AC
Data_8                                                           14
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           50A
DLC                        8
Data_1                    B4
Data_2                    79
Data_3                    8E
Data_4                    5C
Data_5                    84
Data_6                    A9
Data_7                    38
Data_8                    92
Class                Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           50A
DLC                        8
Data_1                    F7
Data_2                    FC
Data_3                    F9
Data_4                    10
Data_5                    1A
Data_6                    39
Data_7                    00
Data_8                    AA
Class                Fuzzing
dtype: object
Timestamp         164    NaN
164    NaN
165    NaN
165    NaN
Na...
Arbitration_ID                                                  2B0
DLC                                                               8
Data_1                                                           F0
Data_2                                                           77
Data_3                                                           47
Data_4                                                           B3
Data_5                                                           DA
Data_6                                                           89
Data_7                                                           3C
Data_8                                                           61
Class                                                       Fuzzing
dtype: object
Timestamp         165                                           ...
Arbitration_ID                                                  44E
DLC                                                               8
Data_1                                                           39
Data_2                                                           CC
Data_3                                                           A2
Data_4                                                           09
Data_5                                                           F2
Data_6                                                           75
Data_7                                                           4E
Data_8                                                           33
Class                                                       Fuzzing
dtype: object

Timestamp         166    164    NaN
164    NaN
165    NaN
165   ...
Arbitration_ID                                                  420
DLC                                                               8
Data_1                                                           65
Data_2                                                           C2
Data_3                                                           38
Data_4                                                           F9
Data_5                                                           BB
Data_6                                                           07
Data_7                                                           B2
Data_8                                                           FD
Class                                                       Fuzzing
dtype: object
Timestamp         167    165                                    ...
Arbitration_ID                                                  140
DLC                                                               8
Data_1                                                           6D
Data_2                                                           57
Data_3                                                           05
Data_4                                                           8E
Data_5                                                           60
Data_6                                                           D0
Data_7                                                           4B
Data_8                                                           F2
Class                                                       Fuzzing
dtype: object
Timestamp         168    166    164    NaN
164    NaN
165    NaN...
Arbitration_ID                                                  490
DLC                                                               8
Data_1                                                           04
Data_2                                                           22
Data_3                                                           6B
Data_4                                                           73
Data_5                                                           DC
Data_6                                                           72
Data_7                                                           8A
Data_8                                                           DB
Class                                                       Fuzzing
dtype: object
Timestamp         1597707827
Arbitration_ID           48C
DLC                        8
Data_1                    BB
Data_2                    78
Data_3                    2F
Data_4                    3C
Data_5                    7E
Data_6                    71
Data_7                    55
Data_8                    08
Class                Fuzzing
dtype: object

In [12]:
data.head(30)

,Timestamp,Arbitration_ID,DLC,Data_1,Data_2,Data_3,Data_4,Data_5,Data_6,Data_7,Data_8,Class
0,1597707827,260,8,6,25,5,30,FF,CF,71,55,Normal
1,1597707827,329,8,4A,C5,7E,8C,31,2D,1,10,Normal
2,1597707827,38D,8,0,0,49,0,90,7F,FE,1,Normal
3,1597707827,420,8,50,1E,0,C8,FC,4F,6A,0,Normal
4,1597707827,421,8,FE,7,0,FF,E3,7F,0,52,Normal
5,1597707827,153,8,20,80,10,FF,0,FF,A0,4E,Normal
6,1597707827,220,8,12,24,7C,0,0,6D,10,F6,Normal
7,1597707827,340,8,0,0,0,24,36,1,25,30,Normal
8,1597707827,389,8,0,0,0,20,0,0,C2,0,Normal
9,1597707827,47F,8,0,EC,FF,FA,0,78,0,36,Normal
10,1597707827,130,8,E4,80,AC,80,0,0,7,95,Normal
11,1597707827,140,8,6C,80,0,6E,20,0,7,E8,Normal
12,1597707827,251,8,59,4,DA,4F,0,45,B8,7F,Normal
13,1597707827,2B0,6,67,0,0,7,CA,5B,NaN,NaN,Normal
14,1597707827,164,4,0,8,1C,FA,NaN,NaN,NaN,NaN,Normal
15,1597707827,356,8,0,0,0,80,1F,0,0,0,Normal
16,1597707827,366,7,26,82,10,25,21,0B,1,NaN,Normal
17,1597707827,367,8,0,0,0,0,5,0,B4,12,Normal
18,1597707827,368,8,0,0C,1,0,2,82,10,44,Normal
19,1597707827,381,8,80,28,42,0,0,EE,12,5,Normal
20,1597707827,387,8,F0,BD,FA,BD,0,71,0D,0,Normal
21,1597707827,394,8,0,0,0,0,E5,3,19,98,Normal
22,1597707827,453,5,0,88,90,0,6F,NaN,NaN,NaN,Normal
23,1597707827,470,8,15,41,1,4,54,50,54,45,Normal
24,1597707827,490,8,0,0,8,21,0,30,3C,BD,Normal
25,1597707827,495,8,0,0,61,0A,1D,2,87,6E,Normal
26,1597707827,500,8,1,7,0,0,0C,0,0C,53,Normal
27,1597707827,260,8,6,25,5,30,FF,CF,71,64,Normal
28,1597707827,391,8,0,0,0,0,0,0,3,24,Normal
29,1597707827,329,8,4A,C5,7E,8C,31,2E,1,10,Normal

In [155]:
test.head(30)

,Timestamp,Arbitration_ID,DLC,Data_1,Data_2,Data_3,Data_4,Data_5,Data_6,Data_7,Data_8,Class
0,1597707827,495,8,9F,F9,F4,E7,27,7E,B9,18,Fuzzing
1,1597707827,43,8,B5,13,22,50,FB,28,41,FA,Fuzzing
2,1597707827,260,8,6,25,5,30,FF,CF,71,55,Normal
3,1597707827,329,8,4A,C5,7E,8C,31,2D,1,10,Normal
4,1597707827,38D,8,0,0,49,0,90,7F,FE,1,Normal
5,1597707827,49F,8,99,68,6A,3C,9E,7C,82,1E,Fuzzing
6,1597707827,53E,8,7B,0F,96,7B,79,02,5D,81,Fuzzing
7,1597707827,420,8,50,1E,0,C8,FC,4F,6A,0,Normal
8,1597707827,421,8,FE,7,0,FF,E3,7F,0,52,Normal
9,1597707827,153,8,20,80,10,FF,0,FF,A0,4E,Normal
10,1597707827,410,8,1F,04,46,C2,E4,CF,26,AC,Fuzzing
11,1597707827,220,8,12,24,7C,0,0,6D,10,F6,Normal
12,1597707827,436,8,D2,AD,1B,5F,98,30,F2,7C,Fuzzing
13,1597707827,340,8,0,0,0,24,36,1,25,30,Normal
14,1597707827,58B,8,0C,44,06,03,E3,DD,7D,A4,Fuzzing
15,1597707827,389,8,0,0,0,20,0,0,C2,0,Normal
16,1597707827,47F,8,0,EC,FF,FA,0,78,0,36,Normal
17,1597707827,53B,8,33,95,77,80,EF,9B,C3,A1,Fuzzing
18,1597707827,381,8,65,DC,E2,33,E5,85,5E,12,Fuzzing
19,1597707827,50C,8,A3,EE,E1,C0,C9,DE,A0,0F,Fuzzing
20,1597707827,130,8,E4,80,AC,80,0,0,7,95,Normal
21,1597707827,140,8,6C,80,0,6E,20,0,7,E8,Normal
22,1597707827,420,8,4F,10,6A,B9,BF,A9,89,4C,Fuzzing
23,1597707827,421,8,D8,C3,2C,0D,44,A1,51,52,Fuzzing
24,1597707827,153,8,25,10,25,8D,69,BA,02,D4,Fuzzing
25,1597707827,251,8,59,4,DA,4F,0,45,B8,7F,Normal
26,1597707827,544,8,2C,9F,0C,61,4F,15,6B,79,Fuzzing
27,1597707827,2B0,6,67,0,0,7,CA,5B,NaN,NaN,Normal
28,1597707827,164,4,0,8,1C,FA,NaN,NaN,NaN,NaN,Normal
29,1597707827,356,8,0,0,0,80,1F,0,0,0,Normal

In [ ]:
(data, 시작, 끝, Attack_data , 패턴 형식)